#!/sbin/busybox sh

. /res/customconfig/customconfig-helper

_ACTIVEPROF=`cat /data/.hulk/.hulk.profile`

case "${_ACTIVEPROF}" in
  battery)
    cp /data/.hulk/battery.profile /data/.hulk/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  balanced)
    cp /data/.hulk/balanced.profile /data/.hulk/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  performance)
    cp /data/.hulk/performance.profile /data/.hulk/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
esac;
