#!/sbin/busybox sh

if [ "a$2" != "a" ];then
echo $2 > /data/.hulk/.hulk.profile
fi

if [ -f /data/.hulk/.hulk.profile ];then
  cat /data/.hulk/.hulk.profile
else
  echo "balanced" > /data/.hulk/.hulk.profile
fi
