#!/sbin/busybox sh

# $1 - "cpuminfreq"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.hulk/.active.profile);
. /data/.hulk/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	cpuminfreq=$2;

	echo "$cpuminfreq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;
	echo "$cpuminfreq" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq;
	echo "$cpuminfreq" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq;
	echo "$cpuminfreq" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq;
fi;

echo ${cpuminfreq};

