#!/sbin/busybox sh

# $1 - "max_online_cpus"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	max_online_cpus=$2;

	case "${max_online_cpus}" in
		4)
			echo "4" > /sys/module/lazyplug/nr_possible_cores;
			echo "4" > /sys/module/msm_hotplug/max_cpus_online;
			echo "4" > /sys/kernel/intelli_plug/max_cpus_online;
		;;
		3)
			echo "3" > /sys/module/lazyplug/nr_possible_cores;
			echo "3" > /sys/module/msm_hotplug/max_cpus_online;
			echo "3" > /sys/kernel/intelli_plug/max_cpus_online;
		;;
		2)
			echo "2" > /sys/module/lazyplug/nr_possible_cores;
			echo "2" > /sys/module/msm_hotplug/max_cpus_online;
			echo "2" > /sys/kernel/intelli_plug/max_cpus_online;
		;;
		1)
			echo "1" > /sys/module/lazyplug/nr_possible_cores;
			echo "1" > /sys/module/msm_hotplug/max_cpus_online;
			echo "1" > /sys/kernel/intelli_plug/max_cpus_online;
		;;
		*)
			max_online_cpus=4;
		;;
	esac;
fi;
echo ${max_online_cpus};

