#!/sbin/busybox sh

# $1 - "cpumaxfreq"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.hulk/.active.profile);
. /data/.hulk/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	cpumaxfreq=$2;

	echo "$cpumaxfreq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
	echo "$cpumaxfreq" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq;
	echo "$cpumaxfreq" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq;
	echo "$cpumaxfreq" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq;
fi;

echo ${cpumaxfreq};

