#!/sbin/busybox sh

# $1 - "cpugov"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.hulk/.active.profile);
. /data/.hulk/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	cpugov=$2;

	echo "$cpugov" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
	echo "$cpugov" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
	echo "$cpugov" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
	echo "$cpugov" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
fi;

echo ${cpugov};

